"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.ageddebtors_sdk import AgedDebtorsSDK
from openapi.attachments import Attachments
from openapi.balancesheet_sdk import BalanceSheetSDK
from openapi.billpayments import BillPayments
from openapi.bills import Bills
from openapi.companyinfo_sdk import CompanyInfoSDK
from openapi.creditnotes import CreditNotes
from openapi.customers import Customers
from openapi.departments import Departments
from openapi.expenses import Expenses
from openapi.invoiceitems import InvoiceItems
from openapi.invoices import Invoices
from openapi.journalentries import JournalEntries
from openapi.ledgeraccounts import LedgerAccounts
from openapi.locations import Locations
from openapi.payments import Payments
from openapi.profitandloss_sdk import ProfitAndLossSDK
from openapi.purchaseorders import PurchaseOrders
from openapi.subsidiaries import Subsidiaries
from openapi.suppliers import Suppliers
from openapi.taxrates import TaxRates
from openapi.trackingcategories import TrackingCategories


class Accounting(BaseSDK):
    tax_rates: TaxRates
    bills: Bills
    invoices: Invoices
    ledger_accounts: LedgerAccounts
    invoice_items: InvoiceItems
    credit_notes: CreditNotes
    customers: Customers
    suppliers: Suppliers
    payments: Payments
    company_info: CompanyInfoSDK
    balance_sheet: BalanceSheetSDK
    profit_and_loss: ProfitAndLossSDK
    journal_entries: JournalEntries
    purchase_orders: PurchaseOrders
    subsidiaries: Subsidiaries
    locations: Locations
    departments: Departments
    attachments: Attachments
    tracking_categories: TrackingCategories
    bill_payments: BillPayments
    expenses: Expenses
    aged_debtors: AgedDebtorsSDK

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.tax_rates = TaxRates(self.sdk_configuration)
        self.bills = Bills(self.sdk_configuration)
        self.invoices = Invoices(self.sdk_configuration)
        self.ledger_accounts = LedgerAccounts(self.sdk_configuration)
        self.invoice_items = InvoiceItems(self.sdk_configuration)
        self.credit_notes = CreditNotes(self.sdk_configuration)
        self.customers = Customers(self.sdk_configuration)
        self.suppliers = Suppliers(self.sdk_configuration)
        self.payments = Payments(self.sdk_configuration)
        self.company_info = CompanyInfoSDK(self.sdk_configuration)
        self.balance_sheet = BalanceSheetSDK(self.sdk_configuration)
        self.profit_and_loss = ProfitAndLossSDK(self.sdk_configuration)
        self.journal_entries = JournalEntries(self.sdk_configuration)
        self.purchase_orders = PurchaseOrders(self.sdk_configuration)
        self.subsidiaries = Subsidiaries(self.sdk_configuration)
        self.locations = Locations(self.sdk_configuration)
        self.departments = Departments(self.sdk_configuration)
        self.attachments = Attachments(self.sdk_configuration)
        self.tracking_categories = TrackingCategories(self.sdk_configuration)
        self.bill_payments = BillPayments(self.sdk_configuration)
        self.expenses = Expenses(self.sdk_configuration)
        self.aged_debtors = AgedDebtorsSDK(self.sdk_configuration)
