"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.connectioncustommappings import ConnectionCustomMappings
from openapi.connections import Connections
from openapi.connectionsettings import ConnectionSettings
from openapi.consumerrequestcounts import ConsumerRequestCounts
from openapi.consumers import Consumers
from openapi.customfields import CustomFields
from openapi.custommappings_sdk import CustomMappingsSDK
from openapi.logs import Logs


class Vault(BaseSDK):
    consumers: Consumers
    consumer_request_counts: ConsumerRequestCounts
    connections: Connections
    connection_settings: ConnectionSettings
    custom_fields: CustomFields
    connection_custom_mappings: ConnectionCustomMappings
    custom_mappings: CustomMappingsSDK
    logs: Logs

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.consumers = Consumers(self.sdk_configuration)
        self.consumer_request_counts = ConsumerRequestCounts(self.sdk_configuration)
        self.connections = Connections(self.sdk_configuration)
        self.connection_settings = ConnectionSettings(self.sdk_configuration)
        self.custom_fields = CustomFields(self.sdk_configuration)
        self.connection_custom_mappings = ConnectionCustomMappings(
            self.sdk_configuration
        )
        self.custom_mappings = CustomMappingsSDK(self.sdk_configuration)
        self.logs = Logs(self.sdk_configuration)
