"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .simpleformfieldoption import SimpleFormFieldOption, SimpleFormFieldOptionTypedDict
from openapi.types import BaseModel
from openapi.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FormFieldOptionGroupTypedDict(TypedDict):
    label: str
    options: List[SimpleFormFieldOptionTypedDict]
    id: NotRequired[str]
    option_type: Literal["group"]


class FormFieldOptionGroup(BaseModel):
    label: str

    options: List[SimpleFormFieldOption]

    id: Optional[str] = None

    OPTION_TYPE: Annotated[
        Annotated[Literal["group"], AfterValidator(validate_const("group"))],
        pydantic.Field(alias="option_type"),
    ] = "group"
