"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getconsumerresponse import GetConsumerResponse, GetConsumerResponseTypedDict
from .unexpectederrorresponse import (
    UnexpectedErrorResponse,
    UnexpectedErrorResponseTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class VaultConsumersOneGlobalsTypedDict(TypedDict):
    app_id: NotRequired[str]
    r"""The ID of your Unify application"""


class VaultConsumersOneGlobals(BaseModel):
    app_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-app-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of your Unify application"""


class VaultConsumersOneRequestTypedDict(TypedDict):
    consumer_id: str
    r"""ID of the consumer to return"""
    app_id: NotRequired[str]
    r"""The ID of your Unify application"""


class VaultConsumersOneRequest(BaseModel):
    consumer_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the consumer to return"""

    app_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-app-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of your Unify application"""


VaultConsumersOneResponseTypedDict = TypeAliasType(
    "VaultConsumersOneResponseTypedDict",
    Union[GetConsumerResponseTypedDict, UnexpectedErrorResponseTypedDict],
)


VaultConsumersOneResponse = TypeAliasType(
    "VaultConsumersOneResponse", Union[GetConsumerResponse, UnexpectedErrorResponse]
)
