workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    accounting:
        inputs:
            - location: https://ci-spec-unify.s3.eu-central-1.amazonaws.com/speakeasy-spec.yml
        overlays:
            - location: ./overlays/accounting-vault-overlay.yml
        transformations:
            - removeUnused: true
            - cleanup: true
        registry:
            location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-accounting-only-oas
targets:
    accounting-py:
        target: python
        source: accounting
        output: ./accounting
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/apideck-k2o/apideck/apideck-accounting-only-oas-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
